services:
  db:
    image: redis:alpine
    hostname: redis
    restart: always
    volumes:
      - db_data:/data
    expose:
      - "6379"

  poller:
    depends_on:
      - db
    image: hackerone-tracker
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: config.yaml
        target: /etc/security/config.yaml
    environment:
      - APP_NAME=poller
      - CONFIG_NAME=poller
    restart: always
    command:
      ["bash", "/usr/local/bin/yaml_to_cli.sh", "/etc/security/config.yaml"]

  security_discord:
    depends_on:
      - db
    image: hackerone-tracker
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: config.yaml
        target: /etc/security/config.yaml

    environment:
      - APP_NAME=discord
      - CONFIG_NAME=discord

    restart: always
    command:
      ["bash", "/usr/local/bin/yaml_to_cli.sh", "/etc/security/config.yaml"]

volumes:
  db_data:
